# Generated by Django 3.1.1 on 2020-09-20 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('middlename', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('status', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('spouse', models.CharField(max_length=50)),
                ('children', models.IntegerField()),
                ('street', models.CharField(max_length=25)),
                ('brgy', models.CharField(max_length=25)),
                ('zipp', models.IntegerField()),
                ('city', models.CharField(max_length=25)),
                ('province', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRegistered', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=20)),
                ('productName', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('stocks', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ReloZone.person')),
                ('dateRegistered', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('ReloZone.person',),
        ),
    ]
